### ISSUE TITLE
Dont works

### ISSUE THREAD

**Issue by MJMODZZ** [y9x/webpack#4]
I was a User of the script build from source code so i could add some really cool function. Now i have 2 problems. If i use my BetterSploit script i get the message The New Loader will be Updated/Installed. I tryed to fix it by my own but its not working. And if i use the standart Cheat Loader i cannot find a game.

**Comment by e9x** [comment]
This script was discontinued a few months ago and hasn't received any updates for a while. Many features are broken such as what you're experiencing.

**Comment by afkvido** [comment]
Sploit still works.

**Comment by MJMODZZ** [comment]
> afkvido

Nah i get the error that the New loader will be updated/installed

**Comment by afkvido** [comment]
Skill issue?
